# Generated by Django 5.2.4 on 2025-07-18 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_sector_unit_sector_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Item de Inventário',
                'verbose_name_plural': 'Categorias de Itens de Inventário',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Stock')),
                ('min_stock_level', models.PositiveIntegerField(default=0, verbose_name='Nível Mínimo de Stock')),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, verbose_name='Unidade de Medida')),
                ('location_description', models.CharField(blank=True, max_length=255, verbose_name='Descrição da Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitemtype', verbose_name='Categoria')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='Fornecedor Padrão')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['item_name'],
            },
        ),
    ]
