# Generated by Django 5.2.4 on 2025-07-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Despesa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Despesa')),
                ('expense_date', models.DateField(verbose_name='Data da Despesa')),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='expense_invoices/', verbose_name='Anexo (Nota Fiscal)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.asset', verbose_name='Ativo Associado')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expensetype', verbose_name='Tipo de Despesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-expense_date'],
            },
        ),
    ]
