# ==============================================================================
# connectit_config/settings.py - Refatorado e Corrigido como Arquiteto de Software Sênior
# ==============================================================================
"""
Django settings for connectit_config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Importar 'os' para o STATIC_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6tp7n168ipz!b02zcdzwjybiqx&l0yj_o101f7rm7mk#_v4gpn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # APPs PADRÃO DO DJANGO (RE-ADICIONADAS - CRUCIAIS!)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Crucial para collectstatic

    # SUAS APPs DO PROJETO
    'contracts',
    'core',
    'expenses',
    # 'finance', # REMOVIDO: Causa ModuleNotFoundError pois a pasta 'finance' não existe.
    'inventory',
    # 'software', # Mantido, mas lembre-se que os modelos Software e SoftwareCategory foram movidos para core.models se não houver um app 'software' dedicado.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'connectit_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ajuste 'DIRS' para incluir templates globais do projeto se você tiver
        'DIRS': [BASE_DIR / 'templates'], # Mantido como estava, aponta para pasta 'templates' na raiz do projeto
        'APP_DIRS': True, # Isso permite que o Django procure templates nas subpastas 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Adicionado para DEBUG=True
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'connectit_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS: Diretórios onde o Django também deve procurar por arquivos estáticos
# Útil para arquivos estáticos globais do projeto (não específicos de uma app)
# Mantido como você tinha, apontando para uma pasta 'static' na raiz do projeto
STATICFILES_DIRS = [
    BASE_DIR / "static", # Isso aponta para C:\industria\connectit_django\static
]

# STATIC_ROOT: O DIRETÓRIO ONDE OS ARQUIVOS ESTÁTICOS SERÃO COLETADOS PELO 'collectstatic'
# ESTE É O DIRETÓRIO QUE SERÁ SERVIDO PELO SERVIDOR WEB EM PRODUÇÃO
# DEVE SER UM DIRETÓRIO DIFERENTE DE QUALQUER PASTA 'static/' OU DE STATICFILES_DIRS
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'