# Generated by Django 5.2.4 on 2025-07-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Contrato')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Contrato')),
                ('contract_object', models.TextField(verbose_name='Objeto do Contrato')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Duração (meses)')),
                ('end_date', models.DateField(blank=True, verbose_name='Data de Fim')),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('payment_day', models.PositiveIntegerField(help_text='Dia do mês em que a fatura vence (1-31)', verbose_name='Dia do Pagamento no Mês')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_assets', models.ManyToManyField(blank=True, to='core.asset', verbose_name='Ativos Vinculados')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier', verbose_name='Fornecedor')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttype', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('em_atraso', 'Em Atraso')], default='pendente', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento Efetivo')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pagamento Agendado',
                'verbose_name_plural': 'Pagamentos Agendados',
                'ordering': ['due_date'],
            },
        ),
    ]
