# Generated by Django 5.2.4 on 2025-07-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_firestore_id_contracttype_firestore_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Contrato', 'verbose_name_plural': 'Tipos de Contratos'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (meses)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
