# Generated by Django 5.2.4 on 2025-07-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contracttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Parcela'),
        ),
    ]
