# Generated by Django 5.2.4 on 2025-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_scheduledpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('paid', 'Pago'), ('waiting', 'Aguardando'), ('completed', 'Concluído'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando'), ('pago', 'Pago'), ('em_atraso', 'Em Atraso')], default='waiting', max_length=20, verbose_name='Status'),
        ),
    ]
