# Generated by Django 5.2.4 on 2025-07-17 19:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Centro de Custo')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Unidade')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('em_uso', 'Em Uso'), ('em_estoque', 'Em Estoque'), ('em_manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='em_estoque', max_length=20, verbose_name='Status')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('internal_tag', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Etiqueta Interna')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota Fiscal')),
                ('lease_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Locação/Compra')),
                ('contract_duration_months', models.IntegerField(blank=True, null=True, verbose_name='Duração do Contrato (meses)')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('invoice_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Nota Fiscal')),
                ('lease_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Locação/Início do Contrato')),
                ('delivery_activation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação/Entrega')),
                ('contract_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim do Contrato')),
                ('deactivation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação')),
                ('exclusion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão/Baixa')),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operacional')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Processador')),
                ('memory', models.CharField(blank=True, max_length=50, null=True, verbose_name='Memória RAM')),
                ('office_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do Office')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('imei', models.CharField(blank=True, max_length=15, null=True, verbose_name='IMEI')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_assets', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_assets', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado Com')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assettype', verbose_name='Tipo de Ativo')),
                ('assigned_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.costcenter', verbose_name='Centro de Custo')),
                ('assigned_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sector', verbose_name='Setor Designado')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='Fornecedor')),
                ('assigned_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Unidade Designada')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.asset_attachment_path, verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Unidade'),
        ),
    ]
