# Generated by Django 5.2.4 on 2025-07-18 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_firestore_id_assettype_firestore_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='unit',
        ),
        migrations.AddField(
            model_name='sector',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter', verbose_name='Centro de Custo'),
        ),
    ]
