# Generated by Django 5.2.4 on 2025-07-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sector_unit_sector_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade de Medida')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('status', models.CharField(default='disponivel', max_length=50, verbose_name='Status do Item')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Software',
                'verbose_name_plural': 'Categorias de Software',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total do Ativo'),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField(verbose_name='Data do Registro')),
                ('type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo de Registro')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter', verbose_name='Centro de Custo Associado')),
            ],
            options={
                'verbose_name': 'Registro Financeiro',
                'verbose_name_plural': 'Registros Financeiros',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Software')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão')),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Chave de Licença')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de Compra')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('asset', models.ManyToManyField(blank=True, related_name='installed_software', to='core.asset', verbose_name='Ativos Instalados Em')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='Fornecedor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.softwarecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['name'],
            },
        ),
    ]
