# Generated by Django 5.2.4 on 2025-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventoryitem_softwarecategory_asset_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando'), ('completed', 'Concluído'), ('em_uso', 'Em Uso'), ('em_estoque', 'Em Estoque'), ('em_manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='em_estoque', max_length=20, verbose_name='Status'),
        ),
    ]
