# Generated by Django 5.2.4 on 2025-08-06 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_asset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='memory',
        ),
        migrations.AddField(
            model_name='asset',
            name='memory_gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memória (GB)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Designado'),
        ),
    ]
