# Generated by Django 5.2.4 on 2025-08-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_asset_memory_asset_memory_gb_alter_asset_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
